using SwipeJobs.Domain.Enums;

namespace SwipeJobs.Application.Common.Dtos;

public record JobDto(
    Guid Id,
    string Title,
    string Description,
    Guid CompanyId,
    string Company,
    string? CompanyLogoUrl,
    string? CompanyBannerUrl,
    string? CompanySlug,
    string? CompanyWebsite,
    string? CompanyLinkedInUrl,
    string? CompanyIndustry,
    string? CompanySize,
    string? CompanyDescription,
    string? Location,
    string? City,
    JobCategory Category,
    JobLevel Level,
    bool IsRemote,
    bool IsActive,
    bool IsArchived,
    decimal? SalaryMin,
    decimal? SalaryMax,
    DateTime? ExpiresAt,
    string? ExternalUrl,
    string? JobImageUrl,
    string? AiGeneratedImageUrl,
    Guid SourceId,
    string? SourceName,
    string? SourceLogoUrl,
    SourceTrustLevel SourceTrustLevel,
    int SourceTrustScore,
    IReadOnlyList<TagDto> Tags,
    IReadOnlyList<string> TrendingBadges,
    string? DisplayTitle,
    string? DisplayCompany,
    string? DisplaySalary,
    string? DisplayLocation,
    IReadOnlyList<string> DisplaySkills,
    string? DisplaySummary,
    DateTime CreatedAt,
    DateTime? UpdatedAt);

public record CreateJobDto(
    string Title,
    string Description,
    Guid CompanyId,
    string? Location,
    string? City,
    JobCategory Category,
    JobLevel Level,
    bool IsRemote,
    decimal? SalaryMin,
    decimal? SalaryMax,
    DateTime? ExpiresAt,
    string? ExternalUrl,
    string? JobImageUrl,
    string? AiGeneratedImageUrl,
    Guid SourceId,
    IReadOnlyList<Guid>? TagIds);

public record UpdateJobDto(
    string Title,
    string Description,
    Guid CompanyId,
    string? Location,
    string? City,
    JobCategory Category,
    JobLevel Level,
    bool IsRemote,
    bool IsActive,
    decimal? SalaryMin,
    decimal? SalaryMax,
    DateTime? ExpiresAt,
    string? ExternalUrl,
    string? JobImageUrl,
    string? AiGeneratedImageUrl,
    Guid SourceId,
    IReadOnlyList<Guid>? TagIds);

public record JobQueryDto(
    string? Search,
    int Page = 1,
    int PageSize = 10,
    string SortBy = "createdAt",
    string SortOrder = "desc",
    JobCategory? Category = null,
    string? City = null,
    bool? IsRemote = null,
    decimal? SalaryMin = null,
    string? Tags = null,
    Guid? CompanyId = null,
    string? CompanySlug = null);
